name: Free Automation Test

on:
  schedule:
    - cron: "*/5 * * * *"   # har 5 minute me run
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: |
          echo "ðŸš€ GitHub Actions is working!"
          date
          
